'use client'
import { useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import {
  FileEdit, Loader2, Paperclip, Sparkles, Clock,
  ExternalLink, ArrowLeft, ChevronDown, ChevronRight, X, Search,
} from 'lucide-react'
import { api } from '@/lib/api'
import { MicButton } from '@/components/MicButton'

// ── Constants ─────────────────────────────────────────────────────────────────

const ATTACH_TYPES = [
  { ext: 'PDF',  desc: 'Portable Document Format' },
  { ext: 'DOCX', desc: 'Word Document' },
  { ext: 'TXT',  desc: 'Plain Text' },
  { ext: 'MD',   desc: 'Markdown' },
]

interface DocHistoryEntry {
  shareToken: string
  title: string
  createdAt: string
}

function loadHistory(): DocHistoryEntry[] {
  if (typeof window === 'undefined') return []
  try {
    return JSON.parse(localStorage.getItem('collabdocs_history') ?? '[]')
  } catch {
    return []
  }
}

function fuzzyMatch(query: string, text: string): boolean {
  const q = query.toLowerCase()
  const t = text.toLowerCase()
  if (t.includes(q)) return true
  let qi = 0
  for (let i = 0; i < t.length && qi < q.length; i++) {
    if (t[i] === q[qi]) qi++
  }
  return qi === q.length
}

function saveToHistory(entry: DocHistoryEntry) {
  const history = loadHistory()
  const updated = [entry, ...history.filter((h) => h.shareToken !== entry.shareToken)].slice(0, 50)
  localStorage.setItem('collabdocs_history', JSON.stringify(updated))
}

type Mode = null | 'ai'

// ── Component ─────────────────────────────────────────────────────────────────

export default function HomePage() {
  const router = useRouter()
  const [mode, setMode] = useState<Mode>(null)

  // Sidebar state
  const [docsCollapsed, setDocsCollapsed] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')

  // AI Assist state
  const [brief, setBrief] = useState('')
  const [pendingFiles, setPendingFiles] = useState<File[]>([])
  const [attachTooltip, setAttachTooltip] = useState(false)

  // Loading / error
  const [starting, setStarting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Document history
  const [history, setHistory] = useState<DocHistoryEntry[]>([])
  useEffect(() => { setHistory(loadHistory()) }, [])

  // ── Helpers ────────────────────────────────────────────────────────────────

  const resetToHome = () => {
    setMode(null)
    setBrief('')
    setPendingFiles([])
    setError(null)
  }

  const handleFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files) return
    setPendingFiles((prev) => [...prev, ...Array.from(e.target.files!)])
    e.target.value = ''
  }, [])

  // ── AI Assist: create doc → generate outline (silent) → start ──────────────

  const handleStart = async () => {
    if (!brief.trim()) return
    setStarting(true)
    setError(null)
    try {
      // The document title is generated by the AI from the brief (returned by
      // getOutline). We only send a placeholder at creation time — the brief is
      // never used as the title.
      const doc = await api.createDocument({ title: 'Untitled document', brief: brief.trim(), type: 'custom' })

      for (const file of pendingFiles) {
        await api.uploadResource(doc.id, file)
      }

      const { sections, title } = await api.getOutline(doc.id)
      await api.confirmOutline(doc.id, sections)
      await api.startWriting(doc.id)

      saveToHistory({ shareToken: doc.shareToken, title, createdAt: new Date().toISOString() })
      setHistory(loadHistory())
      router.push(`/doc/${doc.shareToken}`)
    } catch (err: unknown) {
      setError((err as Error).message ?? 'Something went wrong')
      setStarting(false)
    }
  }

  // ── Render ─────────────────────────────────────────────────────────────────

  const filteredHistory = searchQuery
    ? history.filter((e) => fuzzyMatch(searchQuery, e.title))
    : history

  return (
    <div className="flex min-h-screen bg-gray-100">

      {/* Sidebar — only on landing */}
      {mode === null && (
        <aside className="hidden w-60 shrink-0 flex-col border-r border-gray-200 bg-white px-4 py-8 lg:flex">
          <div className="mb-6 flex items-center gap-2">
            <div className="rounded-xl bg-gray-900 p-2 text-white">
              <FileEdit size={16} />
            </div>
            <span className="font-semibold text-gray-900">CollabDocs</span>
          </div>

          {/* Search */}
          <div className="relative mb-4">
            <Search size={12} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-gray-300" />
            <input
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search docs…"
              className="w-full rounded-md border border-gray-200 bg-gray-50 py-1.5 pl-7 pr-2 text-[13px] text-gray-700 placeholder-gray-400 focus:border-gray-300 focus:outline-none"
            />
          </div>

          {/* Collapsible Documents section */}
          <button
            onClick={() => setDocsCollapsed((c) => !c)}
            className="mb-1 flex w-full items-center gap-1 rounded px-1 py-1 text-xs font-semibold uppercase tracking-wider text-gray-400 hover:bg-gray-50"
          >
            {docsCollapsed ? <ChevronRight size={11} /> : <ChevronDown size={11} />}
            Documents
          </button>

          {!docsCollapsed && (
            filteredHistory.length === 0 ? (
              <p className="px-1 text-sm text-gray-400">
                {searchQuery ? 'No matching docs.' : 'No documents yet.'}
              </p>
            ) : (
              <ul className="flex flex-col gap-0.5 overflow-y-auto">
                {filteredHistory.map((entry) => (
                  <li key={entry.shareToken}>
                    <a
                      href={`/doc/${entry.shareToken}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="group flex items-center gap-2 rounded-lg px-2 py-2 hover:bg-gray-50"
                    >
                      <Sparkles size={11} className="shrink-0 text-indigo-300 group-hover:text-indigo-400" />
                      <p className="min-w-0 flex-1 truncate text-sm text-gray-700 group-hover:text-gray-900">
                        {entry.title}
                      </p>
                      <ExternalLink size={11} className="shrink-0 text-transparent group-hover:text-gray-400" />
                    </a>
                  </li>
                ))}
              </ul>
            )
          )}
        </aside>
      )}

      {/* ── Main content ────────────────────────────────────────────────── */}
      <main className="flex flex-1 flex-col">

        {/* ── Landing ──────────────────────────────────────────────────── */}
        {mode === null && (
          <div className="flex flex-1 flex-col items-center justify-center px-6 py-16">
            <div className="mb-6 flex items-center gap-2.5">
              <div className="rounded-xl bg-gray-900 p-2 text-white">
                <FileEdit size={18} />
              </div>
              <span className="text-lg font-semibold text-gray-900">CollabDocs</span>
            </div>

            <h1 className="mb-10 text-center text-4xl font-bold tracking-tight text-gray-900">
              Build documents faster
            </h1>

            <button
              onClick={() => setMode('ai')}
              className="group flex w-full max-w-sm flex-col items-center gap-4 rounded-2xl border border-gray-200 bg-white p-7 text-center transition-all hover:border-indigo-300 hover:shadow-md active:scale-[0.98]"
            >
              <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-600 text-white shadow-sm">
                <Sparkles size={20} />
              </div>
              <div>
                <p className="text-lg font-bold text-gray-900">AI Assist</p>
                <p className="mt-1.5 text-sm leading-relaxed text-gray-500">
                  Give the AI Writer context for the document you want. It drafts a starter version you can edit and build on together.
                </p>
              </div>
              <p className="text-sm font-medium text-indigo-600 group-hover:underline">
                Start building →
              </p>
            </button>
          </div>
        )}

        {/* ── AI Assist ────────────────────────────────────────────────── */}
        {mode === 'ai' && (
          <div className="relative flex flex-1 flex-col items-center justify-center px-6 py-16">

            {/* Back */}
            <button
              onClick={resetToHome}
              className="absolute left-6 top-6 flex items-center gap-1.5 text-sm text-gray-400 hover:text-gray-700"
            >
              <ArrowLeft size={14} /> Back
            </button>

            {/* Heading */}
            <h1 className="mb-3 text-center text-4xl font-bold tracking-tight text-gray-900" style={{ fontFamily: 'Georgia, serif' }}>
              What should we write?
            </h1>
            <p className="mb-8 text-center text-base text-gray-500">
              Describe the document you want to build to help AI get starter context
            </p>

            {/* Card */}
            <div className="w-full max-w-xl overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm">
              {/* Textarea */}
              <textarea
                value={brief}
                onChange={(e) => setBrief(e.target.value)}
                placeholder=""
                rows={7}
                autoFocus
                className="w-full resize-none px-6 pb-3 pt-6 text-sm text-gray-800 focus:outline-none"
              />

              {/* Pending file chips */}
              {pendingFiles.length > 0 && (
                <div className="flex flex-wrap gap-2 px-6 pb-3">
                  {pendingFiles.map((f, i) => (
                    <span
                      key={i}
                      className="flex items-center gap-1.5 rounded-full border border-gray-200 bg-gray-50 px-2.5 py-1 text-xs text-gray-600"
                    >
                      {f.name}
                      <button
                        onClick={() => setPendingFiles((prev) => prev.filter((_, j) => j !== i))}
                        className="text-gray-400 hover:text-gray-700"
                      >
                        <X size={11} />
                      </button>
                    </span>
                  ))}
                </div>
              )}

              {/* Bottom toolbar */}
              <div className="flex items-center gap-2 border-t border-gray-100 px-4 py-3">

                {/* Paperclip with hover info overlay */}
                <div
                  className="relative"
                  onMouseEnter={() => setAttachTooltip(true)}
                  onMouseLeave={() => setAttachTooltip(false)}
                >
                  <label className="flex cursor-pointer items-center justify-center rounded-lg p-1.5 text-gray-400 hover:bg-gray-100 hover:text-gray-600">
                    <Paperclip size={17} />
                    <input
                      type="file"
                      multiple
                      accept=".pdf,.docx,.txt,.md,.markdown"
                      className="hidden"
                      onChange={handleFileSelect}
                    />
                  </label>

                  {attachTooltip && (
                    <div className="absolute bottom-full left-0 z-20 mb-2 w-52 rounded-xl border border-gray-200 bg-white p-3 shadow-lg">
                      <p className="mb-2 text-xs font-semibold text-gray-500">Supported attachments</p>
                      <div className="flex flex-col gap-1.5">
                        {ATTACH_TYPES.map(({ ext, desc }) => (
                          <div key={ext} className="flex items-center gap-2">
                            <span className="w-10 rounded bg-gray-100 px-1.5 py-0.5 text-center font-mono text-xs font-medium text-gray-600">
                              {ext}
                            </span>
                            <span className="text-xs text-gray-400">{desc}</span>
                          </div>
                        ))}
                      </div>
                      <p className="mt-2.5 text-xs text-gray-400">Up to 20 MB per file</p>
                    </div>
                  )}
                </div>

                {/* Voice input */}
                <MicButton
                  onTranscript={(t) => setBrief((prev) => (prev ? `${prev} ${t}` : t))}
                  size="md"
                />

                {/* Start writing */}
                <button
                  onClick={handleStart}
                  disabled={!brief.trim() || starting}
                  className="ml-auto flex items-center gap-2 rounded-xl bg-gray-900 px-5 py-2 text-sm font-semibold text-white hover:bg-gray-800 disabled:opacity-40"
                >
                  {starting ? (
                    <><Loader2 size={14} className="animate-spin" />Working…</>
                  ) : (
                    'Start writing →'
                  )}
                </button>
              </div>
            </div>

            {error && <p className="mt-4 text-sm text-red-500">{error}</p>}
          </div>
        )}

      </main>
    </div>
  )
}
